name: "Up version, build and upload the exported folder to valist"

on:
  push:
    branches:
      - master

jobs:
  valist-publish:
    name: start building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build and export Next.js app
        run: |
          cd frontend
          npm install
          npm run build
          npm run export

      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: upload to valist
        uses: valist-io/valist-github-action@v2.5.6
        with:
          private-key: ${{ secrets.VALIST_KEY }}
          account: yanukadeneth99
          project: whitelist-dapp
          release: github-action-${{ env.TIMESTAMP }}
          path: frontend/out
